GET http://localhost:3000/books/


### Access a book using id 

GET http://localhost:3000/books/45/


### Adding a new book api 

POST http://localhost:3000/books/ 
Content-Type: application/json

{
    "title": "How to get over it",
    "authorId": 2,
    "rating": 4,
    "ratingCount": 1444244,
    "reviewCount": 1234343,
    "description": "Know the obstacles faced by the lord and how he overcame it",
    "pages": 300,
    "dateOfPublication": "April 4th 2003",
    "edition_language": "Sanskrit",
    "price": 200,
    "onlineStores": "Amazon"
}

### Updating a book api 
PUT http://localhost:3000/books/45/
Content-Type: "application/json"

{
    "title": "Obstacles faced by lord",
}

### Deleting a book api 

DELETE http://localhost:3000/books/45